version: '2'
services:
  phpfpm:
    image: 'bitnami/php-example:0.0.1'
  nginx:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - ./server_blocks/myapp.conf:/opt/bitnami/nginx/conf/server_blocks/myapp.conf
