## This is test deployment for Kubernetes platforms.
## This is not intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-php-fpm
  name: test-php-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-php-fpm
  template:
    metadata:
      labels:
        app: test-php-fpm
    spec:
      containers:
      - image: bitnami/php-fpm
        name: php-fpm
